// <auto-generated />
using System;
using Mesa.Blackjack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mesa.BlackJack.Data.Migrations
{
    [DbContext(typeof(BlackJackContext))]
    [Migration("20230824013301_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mesa.BlackJack.Model.CardBlackJack", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BlackJackId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("IdJugador")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OriginalValue")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Representation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SubValue")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("TypeOfCardId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id", "BlackJackId");

                    b.HasIndex("BlackJackId")
                        .HasDatabaseName("IX_CardBlackJack_BlackJackId");

                    b.ToTable("MazoBlackJack", (string)null);
                });

            modelBuilder.Entity("Mesa.BlackJack.Model.HistoryBlackJack", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BlackJackId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdJugador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logger")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("contadorMazo")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("Id", "BlackJackId");

                    b.HasIndex("BlackJackId")
                        .HasDatabaseName("IX_HistoryBlackJack_BlackJackId");

                    b.ToTable("BlackJack_History", (string)null);
                });

            modelBuilder.Entity("Mesa.Blackjack.Blackjack", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ContadorMazo")
                        .HasColumnType("int");

                    b.Property<string>("IdRequest")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_BlackJack_Id");

                    b.HasIndex("IdRequest")
                        .IsUnique();

                    b.ToTable("Blackjacks");
                });

            modelBuilder.Entity("Mesa.Blackjack.GameRequestBackJack", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AcceptedPlayerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoJuego")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GameRequest", (string)null);
                });

            modelBuilder.Entity("Mesa_SV.BlackJack.DeckOfCards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(14)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("DeckOfCard", (string)null);
                });

            modelBuilder.Entity("Mesa.Blackjack.Blackjack", b =>
                {
                    b.HasOne("Mesa.Blackjack.GameRequestBackJack", null)
                        .WithOne("backjack")
                        .HasForeignKey("Mesa.Blackjack.Blackjack", "IdRequest")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mesa.Blackjack.GameRequestBackJack", b =>
                {
                    b.OwnsMany("Mesa_SV.InfoJugador", "PlayerInfo", b1 =>
                        {
                            b1.Property<string>("GameRequestBackJackId")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("IdContextWS")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("IdUser")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("GameRequestBackJackId", "Id");

                            b1.ToTable("InfoJugador");

                            b1.WithOwner()
                                .HasForeignKey("GameRequestBackJackId");
                        });

                    b.Navigation("PlayerInfo");
                });

            modelBuilder.Entity("Mesa_SV.BlackJack.DeckOfCards", b =>
                {
                    b.OwnsMany("Mesa_SV.BlackJack.Model.Barajas.Card", "Cards", b1 =>
                        {
                            b1.Property<int>("DeckOfCardsId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("OriginalValue")
                                .HasMaxLength(50)
                                .HasColumnType("int");

                            b1.Property<string>("Representation")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("SubValue")
                                .HasMaxLength(50)
                                .HasColumnType("int");

                            b1.Property<int>("TypeOfCardId")
                                .HasMaxLength(50)
                                .HasColumnType("int");

                            b1.HasKey("DeckOfCardsId", "Id");

                            b1.ToTable("DeckOfCard_Cards", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DeckOfCardsId");
                        });

                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Mesa.Blackjack.GameRequestBackJack", b =>
                {
                    b.Navigation("backjack");
                });
#pragma warning restore 612, 618
        }
    }
}
